version: "3.0"
networks:
  my-net:
services:
  spring-demo:
    image: spring-boot-app
    ports:
      - "9292:9090"
    networks:
      - my-net
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8
    networks:
      - my-net
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb  

